type Operator = '+' | '-' | '*' | '/';

export const createLandscapeButtons = ({
    handleClearPress,
    handleNumberPress,
    handleOperatorPress,
    handleEqualPress,
    handleSpecialFunctionPress,
    handleTrigFunctionPress,
    handleRadToggle,
    handleMemoryPress,
    handleToggleSign,
}: {
    handleClearPress: () => void;
    handleNumberPress: (value: string) => void;
    handleOperatorPress: (operator: Operator) => void;
    handleEqualPress: () => void;
    handleSpecialFunctionPress: (func: string) => void,
    handleTrigFunctionPress: (func: string) => void,
    handleRadToggle: () => void
    handleMemoryPress: (func: string) => void,
    handleToggleSign: () => void;
}) => [
    /* First row*/
    {
        title: '(',
        backgroundColor: '#636466',
        color: '#e8e9ea',
        borderColor: '#555759',
        disable: false,
        onPress: () => handleNumberPress('('),
    },
    {
        title: ')',
        backgroundColor: '#636466',
        color: '#e8e9ea',
        borderColor: '#555759',
        disable: false,
        onPress: () => handleNumberPress(')'),

    },
    {
        title: 'mc',
        backgroundColor: '#636466',
        color: '#e8e9ea',
        borderColor: '#555759',
        disable: false,
        onPress: () => handleMemoryPress('MC'),
    },
    {
        title: 'm+',
        backgroundColor: '#636466',
        color: '#e8e9ea',
        borderColor: '#555759',
        disable: false,
        onPress: () => handleMemoryPress('M+'),
    },
    {
        title: 'm-',
        backgroundColor: '#636466',
        color: '#e8e9ea',
        borderColor: '#555759',
        disable: false,
        onPress: () => handleMemoryPress('M-'),
    },
    {
        title: 'mr',
        backgroundColor: '#636466',
        color: '#e8e9ea',
        borderColor: '#555759',
        disable: false,
        onPress: () => handleMemoryPress('MR'),
    },
    {
        title: 'AC',
        backgroundColor: '#636466',
        color: '#e8e9ea',
        borderColor: '#555759',
        disable: false,
        onPress: () => handleClearPress(),
    },
    {
        title: '+/-',
        backgroundColor: '#636466',
        color: '#e8e9ea',
        borderColor: '#555759',
        disable: false,
        onPress: () => handleToggleSign(),
    },
    {
        title: '%',
        backgroundColor: '#636466',
        color: '#e8e9ea',
        borderColor: '#555759',
        disable: false,
        onPress: () => handleNumberPress('%'),
    },
    {
        title: '/',
        backgroundColor: '#ff9a00',
        color: '#e8e9ea',
        borderColor: '#555759',
        disable: false,
        onPress: () => handleOperatorPress('/')
    },
    /* Second Row */
    {
        title: '2nd',
        backgroundColor: '#636466',
        color: '#e8e9ea',
        borderColor: '#555759',
        disable: false,
        onPress: () => {},
    },
    {
        title: 'x^2',
        backgroundColor: '#636466',
        color: '#e8e9ea',
        borderColor: '#555759',
        disable: false,
        onPress: () => handleSpecialFunctionPress('x^2'),
    },
    {
        title: 'x^3',
        backgroundColor: '#636466',
        color: '#e8e9ea',
        borderColor: '#555759',
        disable: false,
        onPress: () => handleSpecialFunctionPress('x^3'),
    },
    {
        title: 'x^y',
        backgroundColor: '#636466',
        color: '#e8e9ea',
        borderColor: '#555759',
        disable: false,
        onPress: () => handleSpecialFunctionPress('test'),
    },
    {
        title: 'e^x',
        backgroundColor: '#636466',
        color: '#e8e9ea',
        borderColor: '#555759',
        disable: false,
        onPress: () => handleSpecialFunctionPress('e^x'),
    },
    {
        title: '10^x',
        backgroundColor: '#636466',
        color: '#e8e9ea',
        borderColor: '#555759',
        disable: false,
        onPress: () => handleNumberPress('10^'),
    },
    {
        title: '7',
        backgroundColor: '#636466',
        color: '#e8e9ea',
        borderColor: '#555759',
        disable: false,
        onPress: () => handleNumberPress('7'),
    },
    {
        title: '8',
        backgroundColor: '#636466',
        color: '#e8e9ea',
        borderColor: '#555759',
        disable: false,
        onPress: () => handleNumberPress('8'),
    },
    {
        title: '9',
        backgroundColor: '#636466',
        color: '#e8e9ea',
        borderColor: '#555759',
        disable: false,
        onPress: () => handleNumberPress('9'),
    },
    {
        title: 'x',
        backgroundColor: '#ff9a00',
        color: '#e8e9ea',
        borderColor: '#555759',
        disable: false,
        onPress: () => handleOperatorPress('*')
    },
    /* Third Row */
    {
        title: '1/x',
        backgroundColor: '#636466',
        color: '#e8e9ea',
        borderColor: '#555759',
        disable: false,
        onPress: () => {},
    },
    {
        title: '√',
        backgroundColor: '#636466',
        color: '#e8e9ea',
        borderColor: '#555759',
        disable: false,
        onPress: () => handleSpecialFunctionPress('√2'),
    },
    {
        title: '∛',
        backgroundColor: '#636466',
        color: '#e8e9ea',
        borderColor: '#555759',
        disable: false,
        onPress: () => handleSpecialFunctionPress('∛'),
    },
    {
        title: 'x√y',
        backgroundColor: '#636466',
        color: '#e8e9ea',
        borderColor: '#555759',
        disable: false,
        onPress: () => handleSpecialFunctionPress('x√y'),
    },
    {
        title: 'ln',
        backgroundColor: '#636466',
        color: '#e8e9ea',
        borderColor: '#555759',
        disable: false,
        onPress: () => handleSpecialFunctionPress('ln'),
    },
    {
        title: 'log10',
        backgroundColor: '#636466',
        color: '#e8e9ea',
        borderColor: '#555759',
        disable: false,
        onPress: () => handleSpecialFunctionPress('log10'),
    },
    {
        title: '4',
        backgroundColor: '#636466',
        color: '#e8e9ea',
        borderColor: '#555759',
        disable: false,
        onPress: () => handleNumberPress('4'),
    },
    {
        title: '5',
        backgroundColor: '#636466',
        color: '#e8e9ea',
        borderColor: '#555759',
        disable: false,
        onPress: () => handleNumberPress('5'),
    },
    {
        title: '6',
        backgroundColor: '#636466',
        color: '#e8e9ea',
        borderColor: '#555759',
        disable: false,
        onPress: () => handleNumberPress('6'),
    },
    {
        title: '-',
        backgroundColor: '#ff9a00',
        color: '#e8e9ea',
        borderColor: '#555759',
        disable: false,
        onPress: () => handleOperatorPress('-')
    },
    /* Fourth Row */
    {
        title: 'X!',
        backgroundColor: '#636466',
        color: '#e8e9ea',
        borderColor: '#555759',
        disable: false,
        onPress: () => handleSpecialFunctionPress('x!'),
    },
    {
        title: 'sin',
        backgroundColor: '#636466',
        color: '#e8e9ea',
        borderColor: '#555759',
        disable: false,
        onPress: () => handleTrigFunctionPress('sin'),
    },
    {
        title: 'cos',
        backgroundColor: '#636466',
        color: '#e8e9ea',
        borderColor: '#555759',
        disable: false,
        onPress: () => handleTrigFunctionPress('cos'),
    },
    {
        title: 'tan',
        backgroundColor: '#636466',
        color: '#e8e9ea',
        borderColor: '#555759',
        disable: false,
        onPress: () => handleTrigFunctionPress('tan'),
    },
    {
        title: 'e',
        backgroundColor: '#636466',
        color: '#e8e9ea',
        borderColor: '#555759',
        disable: false,
        onPress: () => handleSpecialFunctionPress('e'),
    },
    {
        title: 'EE',
        backgroundColor: '#636466',
        color: '#e8e9ea',
        borderColor: '#555759',
        disable: false,
        onPress: () => handleSpecialFunctionPress('EE'),
    },
    {
        title: '1',
        backgroundColor: '#636466',
        color: '#e8e9ea',
        borderColor: '#555759',
        disable: false,
        onPress: () => handleNumberPress('1'),
    },
    {
        title: '2',
        backgroundColor: '#636466',
        color: '#e8e9ea',
        borderColor: '#555759',
        disable: false,
        onPress: () => handleNumberPress('2'),
    },
    {
        title: '3',
        backgroundColor: '#636466',
        color: '#e8e9ea',
        borderColor: '#555759',
        disable: false,
        onPress: () => handleNumberPress('3'),
    },
    {
        title: '+',
        backgroundColor: '#ff9a00',
        color: '#e8e9ea',
        borderColor: '#555759',
        disable: false,
        onPress: () => handleOperatorPress('+')
    },
    /* Fifth Row */
    {
        title: 'Rad',
        backgroundColor: '#636466',
        color: '#e8e9ea',
        borderColor: '#555759',
        disable: false,
        onPress: () => handleRadToggle,
    },
    {
        title: 'sinh',
        backgroundColor: '#636466',
        color: '#e8e9ea',
        borderColor: '#555759',
        disable: false,
        onPress: () => handleTrigFunctionPress('sinh'),
    },
    {
        title: 'cosh',
        backgroundColor: '#636466',
        color: '#e8e9ea',
        borderColor: '#555759',
        disable: false,
        onPress: () => handleTrigFunctionPress('cosh'),
    },
    {
        title: 'tanh',
        backgroundColor: '#636466',
        color: '#e8e9ea',
        borderColor: '#555759',
        disable: false,
        onPress: () => handleSpecialFunctionPress('tanh'),
    },
    {
        title: 'π',
        backgroundColor: '#636466',
        color: '#e8e9ea',
        borderColor: '#555759',
        disable: false,
        onPress: () => handleSpecialFunctionPress('π'),
    },
    {
        title: 'Rand',
        backgroundColor: '#636466',
        color: '#e8e9ea',
        borderColor: '#555759',
        disable: false,
        onPress: () => handleSpecialFunctionPress('Rand'),
    },
    {
        title: '0',
        backgroundColor: '#636466',
        color: '#e8e9ea',
        borderColor: '#555759',
        disable: false,
        onPress: () => handleNumberPress('0'),
        width: '20%'
    },
    {
        title: ',',
        backgroundColor: '#636466',
        color: '#e8e9ea',
        borderColor: '#555759',
        disable: false,
        onPress: () => handleNumberPress('.'),
    },
    {
        title: '=',
        backgroundColor: '#ff9a00',
        color: '#e8e9ea',
        borderColor: '#555759',
        disable: false,
        onPress: () => handleEqualPress(),
    },

];
