type Operator = '+' | '-' | '*' | '/';

export const createPortraitButtons = ({
    handleClearPress,
    handleNumberPress,
    handleOperatorPress,
    handleEqualPress,
}: {
    handleClearPress: () => void;
    handleNumberPress: (value: string) => void;
    handleOperatorPress: (operator: Operator) => void;
    handleEqualPress: () => void;
}) => [
    {
        title: 'AC',
        backgroundColor: '#636466',
        color: '#e8e9ea',
        borderColor: '#555759',
        disable: false,
        onPress: () => handleClearPress(),
    },
    {
        title: '',
        backgroundColor: '#636466',
        color: 'transparent',
        borderColor: 'transparent',
        disable: true,
        width: '50%',
        onPress: () => {},

    },
    {
        title: '/',
        backgroundColor: '#ff9a00',
        color: '#e8e9ea',
        borderColor: '#555759',
        disable: false,
        onPress: () => handleOperatorPress('/'),
    },
    {
        title: '7',
        backgroundColor: '#636466',
        color: '#e8e9ea',
        borderColor: '#555759',
        disable: false,
        onPress: () => handleNumberPress('7'),
    },
    {
        title: '8',
        backgroundColor: '#636466',
        color: '#e8e9ea',
        borderColor: '#555759',
        disable: false,
        onPress: () => handleNumberPress('8'),
    },
    {
        title: '9',
        backgroundColor: '#636466',
        color: '#e8e9ea',
        borderColor: '#555759',
        disable: false,
        onPress: () => handleNumberPress('9'),
    },
    {
        title: 'x',
        backgroundColor: '#ff9a00',
        color: '#e8e9ea',
        borderColor: '#555759',
        disable: false,
        onPress: () => handleOperatorPress('*'),
    },
    {
        title: '4',
        backgroundColor: '#636466',
        color: '#e8e9ea',
        borderColor: '#555759',
        disable: false,
        onPress: () =>  handleNumberPress('4'),
    },
    {
        title: '5',
        backgroundColor: '#636466',
        color: '#e8e9ea',
        borderColor: '#555759',
        disable: false,
        onPress: () => handleNumberPress('5'),
    },
    {
        title: '6',
        backgroundColor: '#636466',
        color: '#e8e9ea',
        borderColor: '#555759',
        disable: false,
        onPress: () => handleNumberPress('6'),
    },
    {
        title: '-',
        backgroundColor: '#ff9a00',
        color: '#e8e9ea',
        borderColor: '#555759',
        disable: false,
        onPress: () => handleOperatorPress('-'),
    },
    {
        title: '1',
        backgroundColor: '#636466',
        color: '#e8e9ea',
        borderColor: '#555759',
        disable: false,
        onPress: () => handleNumberPress('1'),
    },
    {
        title: '2',
        backgroundColor: '#636466',
        color: '#e8e9ea',
        borderColor: '#555759',
        disable: false,
        onPress: () => handleNumberPress('2'),
    },
    {
        title: '3',
        backgroundColor: '#636466',
        color: '#e8e9ea',
        borderColor: '#555759',
        disable: false,
        onPress: () => handleNumberPress('3'),
    },
    {
        title: '+',
        backgroundColor: '#ff9a00',
        color: '#e8e9ea',
        borderColor: '#555759',
        disable: false,
        onPress: () => handleOperatorPress('+'),
    },
    {
        title: '0',
        backgroundColor: '#636466',
        color: '#e8e9ea',
        borderColor: '#555759',
        disable: false,
        width: '50%',
        onPress: () => handleNumberPress('0'),
    },
    {
        title: ',',
        backgroundColor: '#636466',
        color: '#e8e9ea',
        borderColor: '#555759',
        disable: false,
        onPress: () => handleNumberPress('.'),
    },
    {
        title: '=',
        backgroundColor: '#ff9a00',
        color: '#e8e9ea',
        borderColor: '#555759',
        disable: false,
        onPress: () => handleEqualPress(),
    }
];
